apiVersion: v2
name: penpot
description: A Helm chart for penpot.app
type: application
version: 0.3.0
appVersion: "1.19.0"
home: https://penpot.app/
sources:
  - https://github.com/fabianmp/penpot-helm
maintainers:
  - name: Fabian Zach
    email: fabian.zach@methodpark.de
    url: https://github.com/fabianmp
keywords:
  - penpot
  - penpot.app
  - design
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.8.0
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.14.6
