apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penpot.fullname" . }}-env
type: Opaque
data:
  PENPOT_TENANT: {{ .Values.config.tenant | b64enc }}
  PENPOT_DATABASE_USERNAME: {{ .Values.postgresql.auth.username | b64enc }}
  PENPOT_DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  {{- if .Values.config.smtp.enabled }}
  PENPOT_SMTP_PASSWORD: {{ .Values.config.smtp.password | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.google.enabled }}
  PENPOT_GOOGLE_CLIENT_SECRET: {{ .Values.config.auth.google.secret | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.github.enabled }}
  PENPOT_GITHUB_CLIENT_SECRET: {{ .Values.config.auth.github.secret | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.gitlab.enabled }}
  PENPOT_GITLAB_CLIENT_SECRET: {{ .Values.config.auth.gitlab.secret | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.oidc.enabled }}
  PENPOT_OIDC_CLIENT_SECRET: {{ .Values.config.auth.oidc.secret | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.ldap.enabled }}
  PENPOT_LDAP_BIND_PASSWORD: {{ .Values.config.auth.ldap.bindPassword | b64enc }}
  {{- end }}
